// Generated by https://quicktype.io

export interface CartModel {
    id:        number;
    movieId:   number;
    userId:    number;
    title:     string;
    posterURL: string;
    price:     number;
}
