// Generated by https://quicktype.io

export interface FavoriteModel {
    id:        number;
    userId:    number;
    movieId:   number;
    price:     number;
    posterURL: string;
    title:     string;
}

export interface FavoriteRequestModel {
    userId:    number;
    movieId:   number;
}


