// Generated by https://quicktype.io

export interface MovieDetailModel {
    id:          number;
    title:       string;
    posterURL:   string;
    overview:    string;
    tagLine:     string;
    price:       number;
    avgRating:   number;
    runtime:     number;
    genres:      Genre[];
    trailers:    Trailer[];
    revenue:     number;
    budget:      number;
    releaseDate: string;
    casts:       Cast[];
    reviews:     Review[];
}

export interface Cast {
    id:          number;
    name:        string;
    gender:      null;
    tmdbUrl:     null;
    profilePath: string;
    character:   string;
}

export interface Genre {
    id:   number;
    name: string;
}

export interface Review {
    movieId:    number;
    userId:     number;
    rating:     number;
    reviewText: string;
}

export interface Trailer {
    id:         number;
    name:       string;
    trailerURL: string;
}
