// copy json data
// activate/open the extension json paste 
// ctr shift p find overall search

// Generated by https://quicktype.io

export interface MovieCardModel {
    id:        number;
    title:     string;
    posterURL: string;
}


