// Generated by https://quicktype.io

import { MovieCardModel } from "./MovieCardModel";

export interface PageOfMoviesModel {
    pageIndex:   number;
    pageSize:    number;
    count:       number;
    data:        MovieCardModel[];
    totalPages:  number;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}

