// Generated by https://quicktype.io

import { NumberValueAccessor } from "@angular/forms";

export interface PurchasedModel {
    movieId:        number;
    purchaseDate:   string;
    purchasePrice:  number;
    purchaseNumber: string;
    posterURL:      string;
    title:          string;
}

export interface PurchaseRequestModel {
    movieId:        number;
    userId:  number;
    price: number;

}




