
// Generated by https://quicktype.io

export interface TokenModel {
    Language:    string;
    aud:         string;
    email:       string;
    exp:         number;
    family_name: string;
    given_name:  string;
    iat:         number;
    iss:         string;
    nameid:      number;
    nbf:         number;
}
