// Generated by https://quicktype.io

export interface UserProfileModel {
    id:          number;
    firstname:   string;
    lastname:    string;
    dateOfBirth: string;
    email:       string;
    phone:       string;
}
